const PART1_ZH = ['废墟', '深海', '反应堆', '学园', '腐烂', '东京', '三维', '四次元', '少管所', '流星', '闪光', '南极', '消极', '幽浮', '网路', '暗狱', '离子态', '液态', '黑色', '抱抱', '暴力', '垃圾', '社会', '残暴', '残酷', '工口', '戮尸', '原味', '毛茸茸', '香香', '霹雳', '午夜', '美工刀', '爆浆', '机关枪', '无响应', '手术台', '麻风病', '虚拟', '速冻', '智能', '2000', '甜味', '华丽', '反社会', '玛利亚', '无', '梦之', '蔷薇', '无政府', '酷酷', '西伯利亚', '人造', '法外', '追杀', '通缉', '女子', '微型', '男子', '超', '毁灭', '大型', '绝望', '阴间', '死亡', '坟场', '高科技', '奇妙', '魔法', '极限', '社会主义', '无聊'];
const PART1_EN = ['Ruin', 'Deep Sea', 'Reactor', 'Academy', 'Rotten', 'Tokyo', '3D', '4D', 'Juvenile', 'Meteor', 'Flash', 'Antarctic', 'Passive', 'UFO', 'Cyber', 'Dark Prison', 'Ionic', 'Liquid', 'Black', 'Hug', 'Violent', 'Trash', 'Social', 'Brutal', 'Cruel', 'Erotic', 'Corpse', 'Original', 'Fluffy', 'Fragrant', 'Thunder', 'Midnight', 'Cutter', 'Bursting', 'Machine Gun', 'Unresponsive', 'Surgical', 'Leprosy', 'Virtual', 'Frozen', 'Smart', '2000', 'Sweet', 'Gorgeous', 'Anti-Social', 'Maria', 'Null', 'Dream', 'Rose', 'Anarchy', 'Cool', 'Siberia', 'Artificial', 'Outlaw', 'Hunt', 'Wanted', 'Female', 'Micro', 'Male', 'Ultra', 'Destructive', 'Mega', 'Despair', 'Underworld', 'Death', 'Graveyard', 'High-Tech', 'Wonderful', 'Magic', 'Extreme', 'Socialist', 'Boring'];
const PART1_ES = ['Ruina', 'Mar Profundo', 'Reactor', 'Academia', 'Podrido', 'Tokio', '3D', '4D', 'Juvenil', 'Meteoro', 'Destello', 'Antártico', 'Pasivo', 'OVNI', 'Ciber', 'Prisión Oscura', 'Iónico', 'Líquido', 'Negro', 'Abrazo', 'Violento', 'Basura', 'Social', 'Brutal', 'Cruel', 'Erótico', 'Cadáver', 'Original', 'Mullido', 'Fragante', 'Trueno', 'Medianoche', 'Cúter', 'Estallido', 'Ametralladora', 'Sin Respuesta', 'Quirúrgico', 'Lepra', 'Virtual', 'Congelado', 'Inteligente', '2000', 'Dulce', 'Precioso', 'Antisocial', 'María', 'Nulo', 'Sueño', 'Rosa', 'Anarquía', 'Genial', 'Siberia', 'Artificial', 'Forajido', 'Caza', 'Buscado', 'Femenino', 'Micro', 'Masculino', 'Ultra', 'Destructivo', 'Mega', 'Desesperación', 'Inframundo', 'Muerte', 'Cementerio', 'Alta Tecnología', 'Maravilloso', 'Mágico', 'Extremo', 'Socialista', 'Aburrido'];

const PART2_ZH = ['小丑', '仿生', '纳米', '原子', '丧', '电子', '十字架', '咩咩', '赛博', '野猪', '外星', '窒息', '变态', '触手', '小众', '悲情', '飞行', '绿色', '电动', '铁锈', '碎尸', '电音', '蠕动', '酸甜', '虚构', '乱码', '碳水', '内脏', '脑浆', '血管', '全裸', '绷带', '不合格', '光滑', '标本', '酸性', '碱性', '404', '变身', '反常', '樱桃', '碳基', '矫情', '病娇', '进化', '潮湿', '砂糖', '高潮', '变异', '复合盐', '伏特加', '抑郁', '暴躁', '不爱说话', '废物', '失败', '幻想型', '社恐', '苦涩', '粘液', '浓厚', '快乐', '强制', '中二病', '恶魔', 'emo', '激光', '发射', '限量版', '迷因', '堕落', '放射性'];
const PART2_EN = ['Clown', 'Bionic', 'Nano', 'Atomic', 'Depressed', 'Electronic', 'Cross', 'Baa', 'Cyber', 'Boar', 'Alien', 'Suffocating', 'Perverted', 'Tentacle', 'Niche', 'Tragic', 'Flying', 'Green', 'Electric', 'Rust', 'Dismembered', 'Techno', 'Creeping', 'Sweet-Sour', 'Fictional', 'Garbled', 'Carb', 'Viscera', 'Brain Juice', 'Blood Vessel', 'Naked', 'Bandage', 'Unqualified', 'Smooth', 'Specimen', 'Acidic', 'Alkaline', '404', 'Morphed', 'Abnormal', 'Cherry', 'Carbon-Based', 'Pretentious', 'Yandere', 'Evolved', 'Moist', 'Sugar', 'Climax', 'Mutated', 'Complex Salt', 'Vodka', 'Depressive', 'Grumpy', 'Silent', 'Trash', 'Failure', 'Fantasy', 'Social Phobic', 'Bitter', 'Slime', 'Thick', 'Happy', 'Forced', 'Chuunibyou', 'Demon', 'Emo', 'Laser', 'Launch', 'Limited', 'Meme', 'Fallen', 'Radioactive'];
const PART2_ES = ['Payaso', 'Biónico', 'Nano', 'Atómico', 'Deprimido', 'Electrónico', 'Cruz', 'Baa', 'Ciber', 'Jabalí', 'Alienígena', 'Sofocante', 'Pervertido', 'Tentáculo', 'Nicho', 'Trágico', 'Volador', 'Verde', 'Eléctrico', 'Óxido', 'Desmembrado', 'Techno', 'Rastrero', 'Agridulce', 'Ficticio', 'Ininteligible', 'Carbohidrato', 'Víscera', 'Jugo Cerebral', 'Vaso Sanguíneo', 'Desnudo', 'Vendaje', 'No Calificado', 'Suave', 'Espécimen', 'Ácido', 'Alcalino', '404', 'Mutado', 'Anormal', 'Cereza', 'Base de Carbono', 'Pretencioso', 'Yandere', 'Evolucionado', 'Húmedo', 'Azúcar', 'Clímax', 'Mutante', 'Sal Compleja', 'Vodka', 'Depresivo', 'Gruñón', 'Silencioso', 'Basura', 'Fracaso', 'Fantasía', 'Fobia Social', 'Amargo', 'Baba', 'Espeso', 'Feliz', 'Forzado', 'Chuunibyou', 'Demonio', 'Emo', 'Láser', 'Lanzamiento', 'Limitado', 'Meme', 'Caído', 'Radiactivo'];

const PART3_ZH = ['天使', '精灵', '女孩', '男孩', '宝贝', '小妈咪', '虫', '菇', '公主', '少女', '少年', '1号机', '子', '恐龙', '蜈蚣', '蟑螂', '食人鱼', '小飞船', '舞女', '桃子', '团子', '精', '酱', '废料', '生物', '物质', '奶茶', '搅拌机', '液', '火锅', '祭司', '体', '实验品', '试验体', '小猫咪', '样本', '颗粒', '血块', '汽水', '蛙', '软体', '机器人', '人质', '小熊', '圣母', '胶囊', '乙女', '主义者', '屑', '垢', '污渍', '废人', '毛血旺', '怪人', '肉', '河豚', '豚', '藻类', '唾沫', '咒语', '建筑', '球', '小狗', '碳', '元素', '少先队员', '博士', '糖'];
const PART3_EN = ['Angel', 'Elf', 'Girl', 'Boy', 'Baby', 'Mommy', 'Bug', 'Mushroom', 'Princess', 'Young Girl', 'Young Boy', 'Unit 01', 'Child', 'Dinosaur', 'Centipede', 'Cockroach', 'Piranha', 'Spaceship', 'Dancer', 'Peach', 'Dango', 'Spirit', 'Chan', 'Scrap', 'Creature', 'Matter', 'Milk Tea', 'Blender', 'Fluid', 'Hotpot', 'Priest', 'Body', 'Experiment', 'Subject', 'Kitten', 'Sample', 'Particle', 'Blood Clot', 'Soda', 'Frog', 'Mollusk', 'Robot', 'Hostage', 'Bear', 'Madonna', 'Capsule', 'Maiden', 'Ist', 'Scum', 'Dirt', 'Stain', 'Invalid', 'Spicy Blood', 'Weirdo', 'Meat', 'Pufferfish', 'Pig', 'Algae', 'Saliva', 'Spell', 'Building', 'Ball', 'Puppy', 'Carbon', 'Element', 'Pioneer', 'Doctor', 'Candy'];
const PART3_ES = ['Ángel', 'Elfo', 'Chica', 'Chico', 'Bebé', 'Mami', 'Bicho', 'Seta', 'Princesa', 'Jovencita', 'Jovencito', 'Unidad 01', 'Niño', 'Dinosaurio', 'Ciempiés', 'Cucaracha', 'Piraña', 'Nave Espacial', 'Bailarina', 'Melocotón', 'Dango', 'Espíritu', 'Chan', 'Chatarra', 'Criatura', 'Materia', 'Té con Leche', 'Licuadora', 'Fluido', 'Olla Caliente', 'Sacerdote', 'Cuerpo', 'Experimento', 'Sujeto', 'Gatito', 'Muestra', 'Partícula', 'Coágulo', 'Refresco', 'Rana', 'Molusco', 'Robot', 'Rehén', 'Oso', 'Madonna', 'Cápsula', 'Doncella', 'Ista', 'Escoria', 'Mugre', 'Mancha', 'Inválido', 'Sangre Picante', 'Bicho Raro', 'Carne', 'Pez Globo', 'Cerdo', 'Algas', 'Saliva', 'Hechizo', 'Edificio', 'Bola', 'Cachorro', 'Carbono', 'Elemento', 'Pionero', 'Doctor', 'Caramelo'];

function randomNick(lang = 'en') {
  const pick = (arr) => arr[Math.floor(Math.random() * arr.length)];
  if (lang === "zh") return pick(PART1_ZH) + pick(PART2_ZH) + pick(PART3_ZH);
  if (lang === "es") return pick(PART1_ES) + " " + pick(PART2_ES) + " " + pick(PART3_ES);
  return pick(PART1_EN) + " " + pick(PART2_EN) + " " + pick(PART3_EN);
}

module.exports = { randomNick };
