name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    # SERVER
    - name: Server - Install Dependencies
      run: cd server && npm ci

    - name: Server - Lint
      run: cd server && npm run lint

    - name: Server - Test
      run: cd server && npm run test

    # CLIENT
    - name: Client - Install Dependencies
      run: cd client && npm ci

    - name: Client - Lint
      run: cd client && npm run lint

    - name: Client - Test
      run: cd client && npm run test

    - name: Client - Build
      run: cd client && npm run build
